using System;


   class Aprendiz
    {
       public string TipoIdentificacion { get; set; }
       public string NumeroIdentificacion { get; set; }      
       public string NombresAprendiz { get; set; }
       public string ApellidosAprendiz { get; set; }  
       public DateTime FechaNacimiento { get; set; }
       public string Genero { get; set; }
       public string IdFicha { get; set; }
       public string Estado { get; set; }
       public string EstadoCivil { get; set; }
       public string Direccion { get; set; }
       public string RH{ get; set; }
       public string Email { get; set; }
       public string Telefono { get; set; }
       public string TipoPoblacion { get; set; }
       public string DepertamentoResidencia { get; set; }
       public string MunicipioResidencia { get; set; }
       public string DepertamentoNacimiento { get; set; }
       public string MunicipioNacimiento { get; set; }
       public string Estrato { get; set; }
       public string EPS { get; set; }
       public string TipoRegimen { get; set; }
       public DateTime FechaIngreso { get; set; }
       public string Discapacidad { get; set; }
       public string LibretaMilitar { get; set; }
    }


